### ISSUE TITLE
Improve the code add conditionals

### ISSUE THREAD

**Issue by Pedroemanuelavelar** [Pedroemanuelavelar/auto-install-and-configurate-for-git#3]
Add checks to the code for example to check if the user has git installed, if he has not followed through on the rest of the code, if he has not continued executing the script, also look at the local code that needs to improve the code!

Adicionar verificações no código por exemplo verificar se o usuário tem o git instalado, se ele tiver não seguir para o restante do código, se ele não tiver continuar a execução do script, olhar também no código locais que precisam de melhorar o código!

**Comment by ghost** [comment]
Consigo resolver essa issue

**Comment by ghost** [comment]
#4 Aqui consigo implementar se o git ja esta instalado no sistema
